version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/public_html
    depends_on:
      - php
      - mysql
  php:
    build: ./images/php
    volumes:
      - ./www:/var/www/public_html
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_DATABASE=spring_boot_mysql
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
#      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './mysql:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
#  mysql:
#    container_name: mysql2
#    image: mysql
#    volumes:
#      - ./mysql-data:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#  phpmyadmin2:
#    container_name: phpmyadmin2
#    image: phpmyadmin
#    ports:
#      - 1500:80
#    environment:
#      - PMA_HOST=mysql2
#      - PMA_ARBITRARY=1
#    depends_on:
#      - mysql2