version: "3"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/public_html
    depends_on:
      - php
      - mysql
  php:
    build: ./images/php
    restart: always
    volumes:
      - ./www:/var/www/public_html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.42
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_DATABASE=spring_boot_mysql
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './mysql:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
